name: publish

on:
  workflow_dispatch

jobs:

  build1:
    strategy:
      fail-fast: false
      matrix:
        pkg: [aalib, abook, act, actionlint, adig, aerc, ag, age, agg, alacritty, alass, algernon, ali, aliyun-cli, anchor-cli, antibody, aom, apkeep, apr, aptly, archiver, argparse, args, aria2, aribb24, arping, async++, atuin, autoconf-archive, autogen, automake, autossh, autotools-setup, awk, axel, azcopy, b3sum, bandwhich, base16, base64, bash, basis_universal, bat, bazelisk, bc, bcrypt, bear, bgrep, binaryen, bind, binocle, bitcoin, bk, blake3, blockhash, bmake, botan, bottom, boxes, brook, broot, brotli, brpc, bsdtar, bullet, byacc, c-examples, caddy, caf, cargo-c, cargo-deb, catch2, catimg, ccache, cdrtools, cereal, cfitsio, cflow, cgal, cgif, chafa, cheat, check, chezmoi, chicken, chinese-calendar, choose, cilium-cli, circleci-cli, cli11, clog, cmake, cmark, cmatrix, code-cli, coreutils, cotp, cpio, cppcheck, cppunit, cpuid, cpuinfo, croc, crosstool-ng, crowbook, ctop, cue, cups, curl, curlie, cxxopts, d2, darkhttpd, dasel, dash, delta, difftastic, diffutils, distcc, dmalloc, dns2tcp, dnslookup, dnsmap, dnsx, dog, doggo, dolt, dos2unix]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build2:
    strategy:
      fail-fast: false
      matrix:
        pkg: [dot_static, doxygen, dtc, dua, duf, dufs, dust, e2fsprogs, easyutils, ed, effcee, elfcat, elvish, epsilon, esbuild, ethereum, exa, exhale, exiv2, eza, fakeroot, fcp, fd, fdroidcl, fff, figlet, findent, findutils, fish, flatbuffers, flatc, flock, fnm, fortune, freetype2, frei0r, fselect, fsmon, fswatch, fzf, fzy, g, garble, gat, gawk, gbt, gcc, gcc@12, gdb, gdbm, gdk-pixbuf-tools, gdu, geographiclib, germanium, getopt, gettext-tools, gf, gh, ghr, giflib, gindent, git, git-cliff, git-lfs, gitui, gitwatch, glew, glib-tools, glm, glow, glslviewer, glyr, gmake, gn, gnu-barcode, gnu-which, gnupg, gnuplot, go-md2man, go-tools, godu, gogs, golang, golang@1.21, gomobile, google-benchmark, google-highway, gopls, goreleaser, gosh, gotop, gotty, gox, gperf, gping, gpsim, gputils, grep, grex, groff, gron, grpc-plugins, gsed, gtime, gts, halibut, hashcat, helix, helm, help2man, hexdump, hexyl, htop, htslib, httpx, hugo, hunspell, hunter, hurl, hydroxide, hyperfine, id3lib, ideviceinstaller, incus, invoice, iperf3, itstool, ixwebsocket]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build3:
    strategy:
      fail-fast: false
      matrix:
        pkg: [jackaudio, jasper, jemalloc, jfrog-cli, jj, joshuto, jpegoptim, jq, json-glib, jump, k9s, kcp, kcptun, ko, krb5, lazygit, lcms2, lcov, ldns, less, lexbor, lf, libaec, libao, libasprintf, libasync++, libb2, libb64, libbcrypt, libblake3, libcaca, libcanberra, libcddb, libcdio, libcfitsio, libcgif, libclc, libcpuinfo, libcroco, libcuefile, libcyaml, libdecor, libdiscid, libduktape, libdv, libdvdnav, libexhale, libexiv2, libflac, libflatbuffers, libglfw3, libglm, libglob, libgphoto2, libgraphene, libhwy, libical, libilbc, libimagequant, libintl-lite, libirecovery, libisoburn, libjpeg, liblinear, liblmdb, liblo, libmad, libmaxminddb, libmd, libmesalink, libmetalink, libmhash, libmicrohttpd, libmill, libmimalloc, libminiz, libmms, libmnl, libmpir, libnetpbm, libnng, libopenh264, libphonenumber, libphysfs, libpipeline, libpng++, libpq, libproxy, libpugixml, libqalculate, libqrencode, libquiche, libraqm, librasterlite, librasterlite2, libre, libreplaygain, libressl, libresvg, librist, librsync, librtmp, libsigsegv, libsmi, libspectre, libspng, libsvg, libsvm, libtalloc, libtextstyle, libthai, libtins, libtinyxml2, libtorrent-rasterbar, libtree, libtwolame, libupnp, libusrsctp, libuuid, libuvc, libvidstab, libvips, libwasmtime, libwavpack, libwebm, libwordexp, libxml2@2.11, libyuv]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build4:
    strategy:
      fail-fast: false
      matrix:
        pkg: [libz3, libzim, libzlog, lief, lighttpd, lima, links, livego, llhttp, llvm@14, llvm@15, llvm@16, llvm@17, llvm@18, lmdb, lnd, lodepng, log4cplus, lolcat, lrzip, lsd, lsof, luau, lunatic, lunzip, lychee, lynx, lzop, magic_enum, makepkg, mawk, mcfly, md4c, mdbook, mdcat, mediainfo, mftrace, midnight-commander, mimalloc, minisign, miniz, mkcert, mkcue, mksh, mm-wiki, mold, mono, moreutils, mosh, mozjpeg, mpdecimal, mpg123, mpv, msgpack-c, mujs, mupdf, nano, nanomsg, nap, nasm, navi, ncdu, neofetch, netcat, nethogs, nghttp2, nginx, ngtcp2, ninja, nng, nnn, nsh, nspr, ntbtls, nuclei, nushell, oat++, obfs4proxy, onefetch, open264, openal-soft, opencl-icd-loader, opencore-amr, opencv, openfst, openimageio, openldap, openlibm, openmpi, openslide, openssl, p7zip, packcc, patchelf, pax, pbzip2, pcapplusplus, pcre, pcre2, pegof, pget, physfs, pigz, pipewire, pixman, pjsip, pkg-config, pkgconf, plog, plzip, png, pngcheck, pngquant, pngsplit, pocl, poco, pop, ppkg, procs, progress, proto-cli, psimd, pup, putty, pv, python3-setup, python@3.10, python@3.11.6]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build5:
    strategy:
      fail-fast: false
      matrix:
        pkg: [python@3.12, python@3.9, q, qpdf, quiche, quickjs, ragel, rang, ranger, rapidjson, rclone, re2c, redis, restic, resvg, rhash, ripgrep, ripgrep-all, rlwrap, rsass, rsync, rtorrent, rttr, ruff, rust-analyzer, rustup-init, sassc, scc, sccache, sd, shc, shell2http, shellcheck, shellharden, shiori, silicon, simdjson, six, sjpeg, skcms, sl, socat, soundtouch, speex, spirv-tools, sqlite3, sqlite3_analyzer, srs, srt, starship, stwolame, stylua, subfinder, supervisord, suricata, svn-lite, syncthing, sysdig, sysinfo, szip, talloc, tarlz, tbb, tbls, tbox, tcc, tcl-core, tcpdump, tdu, tealdeer, tectonic, tengo, terragrunt, tesseract, test, tiff, tig, tinysearch, tlrc, tmux, tokei, toml++, toml11, tree, trietool, ttyd, ttygif, ttyrec, tut, tweego, twolame, typos, uctags, unbound, unixodbc, unrar, unzip, uppm, uppm@0.15.1, uppm@0.15.2, uppm@0.15.3, uppm@0.15.4, usbutils, utf8.h, utfcpp, util-linux, valijson, vegeta, virustotal-cli, viu, volta, vsftpd, w3m, walk, wasm-pack, wasm3, wasmer, wasmtime, watchexec, wavpack, webhook, webp, websocketpp, wget, whois, wolfssl, wuzz, x264]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  build6:
    strategy:
      fail-fast: false
      matrix:
        pkg: [x265, xbps, xclip, xh, xmake, xmlrpc-c, xmlto, xmlutils, xmlwf, xorg-libxpresent, xorg-libxscrnsaver, xorg-libxtst, xorriso, xpup, xsltproc, xvid, xxd, yajl, yaml-cpp, yasm, yazi, ycm, youtubedr, yq, yyjson, z3, zig, zip, zlib, zlib-ng, zlog, zls, zola, zopfli, zoxide, zsh, zstd, zsync]

    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.25.0
        with:
          operating_system: netbsd
          version: 9.3
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run sudo pkgin -y update
            run sudo pkgin -y install curl

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
            run chmod +x ppkg

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install ${{ matrix.pkg }}

            for item in $(./ppkg ls-installed)
            do
                ./ppkg pack "$item"

                PACKAGE_SUMMARY="$(./ppkg info-installed "$item" summary)"
                PACKAGE_WEB_URL="$(./ppkg info-installed "$item" web-url)"
                PACKAGE_VERSION="$(./ppkg info-installed "$item" version)"

                PACKAGE_NAME="${item#*/}"

                PACKAGE_FILENAME="$(ls $PACKAGE_NAME-$PACKAGE_VERSION-*.tar.xz)"

                PACKAGE_BIN_SHA="$(./ppkg run sha256sum "$PACKAGE_FILENAME" | cut -d ' ' -f1)"

                PACKAGE_BIN_URL="https://github.com/${{ github.repository }}/releases/download/@TAGNAME@/$PACKAGE_FILENAME"

                cat > "$PACKAGE_NAME.yml" <<EOF
            summary: $PACKAGE_SUMMARY
            webpage: $PACKAGE_WEB_URL
            version: $PACKAGE_VERSION
            bin-url: $PACKAGE_BIN_URL
            bin-sha: $PACKAGE_BIN_SHA
            EOF
            done

      - run: ls

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg }}
          path: |
            ./*.tar.xz
            ./*.yml

  publish:
    needs: [build1, build2, build3, build4, build5, build6]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls

      - run: |
          set -ex

          TAGNAME="$(date +%Y.%m.%d)"

          sed -i "s|@TAGNAME@|$TAGNAME|" *.yml

          mv *.yml formula/

          DIRNAME="uppm-formula-repository-netbsd-9.3-amd64-$TAGNAME"

          install -d "$DIRNAME"

          cp -r formula "$DIRNAME/"

          tar cvJf "$DIRNAME.tar.xz" "$DIRNAME"

          sha256sum *.tar.xz > sha256sums.txt

          cat > notes.md <<EOF
          these packages are created by [xcpkg](https://github.com/leleliu008/xcpkg).

          ## Environment Variables

          **following environment variables should be set for \`git\` package**

          \`\`\`bash
          export GIT_EXEC_PATH="\$GIT_INSTALL_DIR/libexec/git-core"
          export GIT_TEMPLATE_DIR="\$GIT_INSTALL_DIR/share/git-core/templates"
          \`\`\`

          **following environment variables should be set for \`file\` package**

          \`\`\`bash
          export MAGIC="\$FILE_INSTALL_DIR/share/misc/magic.mgc"
          \`\`\`

          ## sha256sum

          \`\`\`
          $(cat sha256sums.txt)
          \`\`\`
          EOF

          gh release create "$TAGNAME" *.tar.xz sha256sums.txt --title "$TAGNAME" --notes-file notes.md

          git config --global user.name  "leleliu008"
          git config --global user.email "leleliu008@gmail.com"

          git pull

          git add formula
          git commit -m "release new version $TAGNAME"
          git push origin master
